### ISSUE TITLE
Support dependencies file

### ISSUE THREAD

**Issue by vopani** [h2oai/nitro#10]
**Is your feature request related to a problem? Please describe.**
Having the requirements part of the core app code is an uncommon practice.

**Describe the solution you'd like**
Nitro to be able to install dependencies from a separate txt file.

**Suggestion solution**
Was thinking something like:
```
nitro run https://raw.githubusercontent.com/h2oai/nitro/main/py/examples/hello.py --requirements https://raw.githubusercontent.com/h2oai/nitro/main/py/examples/requirements.txt
```
(or something better) would be quite useful.

**Additional comments**
It could immediately enable Nitro to be used for existing projects in conjunction with existing workflows (like a pip package/library).

**Comment by lo5** [comment]
> Having the requirements part of the core app code is an uncommon practice.

I agree it's uncommon, but that's probably because there's no way to do it :-)

The primary purpose of `nitro run` is to make single-file Python apps possible. A friend pointed out yesterday there's one in the Java world as well. [Link](https://twitter.com/thej/status/1535458261054660609)  .

`nitro run` makes it possible to have N apps in the same directory, each self-contained with its own requirements, like this directory: https://github.com/h2oai/nitro/tree/main/py/examples.

> It could immediately enable Nitro to be used for existing projects in conjunction with existing workflows (like a pip package/library).

That should already be possible. For example, this can run Wave apps:

```py
# ===
# Setup:
# RUN python -m pip install h2o-wave
# START python -m h2o_wave run wave_todo_list.py
# ===
```

For external requirements, use:

```py
# ===
# Setup:
# GET https://raw.githubusercontent.com/foo/bar/requirements.txt
# RUN python -m pip install -r requirements.txt
# START python -m h2o_wave run wave_todo_list.py
# ===
```

Real example:
```
nitro run https://gist.githubusercontent.com/lo5/fb1609c162c9c20da01fab3501cd7cab/raw/wave_todo_list.py
```

**Comment by vopani** [comment]
`GET` works, thanks!
